// Generated from jira-map.example.yaml by scripts/sync-jira-map-template.ts.
// Do not edit by hand: edit the example and rerun `npm run sync-jira-template -w todo-vault`.
// test/jira-map.test.ts fails when the two disagree.

/** The text a first `jira-map.yaml` is written from, comments and all. */
export const JIRA_MAP_TEMPLATE = [
  "# Jira field mapping.",
  "#",
  "# The desktop app writes this for you: press Jira in the toolbar, connect, then",
  "# use the Mapping tab. It starts from this very text and edits values in place,",
  "# so these comments survive. You can also copy it to <vault>/jira-map.yaml and",
  "# fill it in by hand. Almost every",
  "# value below differs between Jira sites, which is why this is config and not",
  "# code.",
  "#",
  "# To fill in the custom field ids, let the CLI read them off your instance:",
  "#",
  "#   JIRA_EMAIL=you@company.com JIRA_TOKEN=... \\",
  "#     vault jira discover --url https://yoursite.atlassian.net --project ENG",
  "#",
  "# It prints a fragment to paste in here, annotated with the name each id had on",
  "# your site. It reads only the project you name, and writes nothing:",
  "#",
  "#   GET /rest/api/3/project/ENG",
  "#   GET /rest/api/3/issue/createmeta/ENG/issuetypes",
  "#   GET /rest/api/3/issue/createmeta/ENG/issuetypes/{issueTypeId}   (one per type)",
  "#",
  "# Only fields on this project's create screens are considered, so a field that",
  "# exists elsewhere on your site but not here is never proposed.",
  "#",
  "# This file is never sent anywhere. It is used only to build a payload you",
  "# review before anything leaves the machine.",
  "",
  "# Where these items land. This is the Jira project key, not your vault key.",
  "jiraProjectKey: ENG",
  "",
  "# Your Jira site. Links back to created issues are built from it, and a classic",
  "# API token is sent here.",
  "baseUrl: https://yourcompany.atlassian.net",
  "",
  "# \"site\" for a classic API token, sent to baseUrl. \"scoped\" for a scoped token,",
  "# which Atlassian only accepts through its API gateway; the gateway needs the",
  "# site's cloud id, which the app looks up for you.",
  "auth: site",
  "# cloudId: 11111111-2222-3333-4444-555555555555",
  "",
  "# The credential itself is never in this file. The desktop app keeps it in your",
  "# OS credential store; the CLI reads JIRA_EMAIL and JIRA_TOKEN from the",
  "# environment. This file is committed with the vault, so a token here would be",
  "# in its git history for good.",
  "",
  "# Local item type -> Jira issue type NAME as it appears on the create screen.",
  "# Team-managed and company-managed projects often differ here, and some sites",
  "# have renamed \"Story\" to something bespoke.",
  "issueTypes:",
  "  epic: Epic",
  "  story: Story",
  "  task: Task",
  "  bug: Bug",
  "  subtask: Subtask",
  "",
  "# Local priority -> Jira priority name.",
  "priorities:",
  "  highest: Highest",
  "  high: High",
  "  medium: Medium",
  "  low: Low",
  "  lowest: Lowest",
  "",
  "fields:",
  "  # Start date is a custom field on essentially every instance, and the id is",
  "  # different on each one. customfield_10015 is a common default on Jira Cloud",
  "  # but do not trust it — look it up. Leave this out and the push will warn you",
  "  # rather than silently dropping your start dates. Commented out here so a",
  "  # guessed id is never used by accident.",
  "  # startDate: customfield_10015",
  "",
  "  # Story points, or whatever you decided `estimate` means. Also commented out",
  "  # until looked up: team-managed and company-managed projects use different",
  "  # fields for it.",
  "  # estimate: customfield_10016",
  "",
  "  # Only needed on older company-managed projects that still use the Epic Link",
  "  # field instead of the modern `parent` field.",
  "  # epicLink: customfield_10014",
  "",
  "  # Where the local `category` field goes. Either the literal string \"labels\"",
  "  # to fold it into labels (spaces become hyphens), or a customfield id.",
  "  category: labels",
  "",
  "# People, as the vault spells them, to Jira accounts. Jira Cloud identifies a",
  "# person by account id, never by name, so an assignee with no entry here is",
  "# pushed unassigned (and the push says so). The app's Mapping tab fills this in",
  "# by searching the people who can be assigned in the project. Names are matched",
  "# case-insensitively.",
  "people: {}",
  "#  dan okafor: { accountId: \"5b10ac8d82e05b22cc7d4ef5\", displayName: \"Dan Okafor\" }",
  "",
  "# Jira fields the vault has no equivalent for, and what to send in them. Write a",
  "# value the way you would say it: an option's name, a paragraph of text, a",
  "# person's name from people above, a comma list, \"Parent / Child\" for a",
  "# two-level select. The push builds Jira's JSON from it, checked against the",
  "# project's own options, so a name Jira does not offer stops the push and says",
  "# what it does offer. A value already in Jira's shape ({ id: \"10021\" }) is sent",
  "# as it is. \"always\" sends the value on every issue; \"ask\" offers it, prefilled,",
  "# in the push pane, where it can be changed for that one push. issueTypes limits",
  "# a field to the issue types whose create screen has it.",
  "extraFields: {}",
  "#  customfield_10001:",
  "#    name: Team",
  "#    mode: always",
  "#    value: Payments",
  "#  customfield_10100:",
  "#    name: Project objective",
  "#    mode: ask",
  "#    value: Cut checkout time by **half**.",
  "#  fixVersions:",
  "#    name: Fix versions",
  "#    mode: ask",
  "#    value: 1.4, 1.5",
  "#    issueTypes: [Story, Bug]",
  "",
  "# The older form of extraFields: sent on every issue, no names, no asking.",
  "# Still read, and sent exactly as written; the app's Mapping tab offers to move",
  "# these into extraFields.",
  "defaults: {}",
  "",
  "# Local status -> Jira transition name. Not applied yet: issues are created in",
  "# the project's default status, and moving them on after creation is planned,",
  "# not built. Filling this in now does no harm and is read once it is.",
  "statusTransitions:",
  "  in_progress: Start work",
  "  in_review: Ready for review",
  "  blocked: Block",
  "  done: Done",
  "  # Closed locally, but not because the work happened. Most Jira workflows call",
  "  # this \"Won't Do\"; check yours, because the transition name has to match.",
  "  disregard: Won't Do",
].join("\n") + "\n";
